/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.BaseStatusSignal;
import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.MotorOutputConfigs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.controls.CoastOut;
import com.ctre.phoenix6.controls.Follower;
import com.ctre.phoenix6.controls.VelocityVoltage;
import com.ctre.phoenix6.controls.VoltageOut;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.InvertedValue;
import com.ctre.phoenix6.signals.MotorAlignmentValue;
import com.ctre.phoenix6.signals.NeutralModeValue;
import com.ctre.phoenix6.sim.ChassisReference;
import com.ctre.phoenix6.sim.TalonFXSimState;

import edu.wpi.first.epilogue.Logged;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N2;
import edu.wpi.first.math.system.LinearSystem;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.math.system.plant.LinearSystemId;
import edu.wpi.first.units.measure.*;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.simulation.DCMotorSim;
import edu.wpi.first.wpilibj.smartdashboard.Mechanism2d;
import edu.wpi.first.wpilibj.smartdashboard.MechanismLigament2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.RunCommand;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;

/**
 * Flywheel sub-component using dual TalonFX Kraken motors.
 * Not a subsystem – owned and driven by {@link frc.robot.subsystems.Shooter}.
 */
@Logged
public class Flywheel {
    /** Velocity setpoints for the flywheel. */
    public enum FlywheelSetpoint {
        Intake(RotationsPerSecond.of(60)),
        Outtake(RotationsPerSecond.of(-10)),
        Near(RotationsPerSecond.of(50)),
        AgainstHub(RotationsPerSecond.of(29)),
        Pass(RotationsPerSecond.of(40)),
        Far(RotationsPerSecond.of(60)), 
        Autonomous(RotationsPerSecond.of(31));

        /** The velocity target of the setpoint. */
        public final AngularVelocity leaderMotorTarget;

        private FlywheelSetpoint(AngularVelocity leaderMotorTarget) {
            this.leaderMotorTarget = leaderMotorTarget;
        }
    }

    private static final int kNumConfigAttempts = 2;

    private static final double kGearRatio = 1 / 1.5;

    /* leader and follower motors */
    private final CANBus kCANBus = new CANBus("main_canivore");
    private final TalonFX leaderMotor = new TalonFX(8, kCANBus);
    private final TalonFX followerMotor = new TalonFX(9, kCANBus);

    /* device status signals */
    private final StatusSignal<AngularVelocity> leaderMotorVelocity = leaderMotor.getVelocity(false);
    private final StatusSignal<Current> leaderMotorTorqueCurrent = leaderMotor.getTorqueCurrent(false);

    /* controls used by the leader motor */
    private final VelocityVoltage leaderMotorSetpointRequest = new VelocityVoltage(0);
    private final CoastOut coastRequest = new CoastOut();

    /* controls used by the follower motor */
    private final Follower followerMotorSetpointRequest = new Follower(8, MotorAlignmentValue.Opposed);

    /* simulation */
    private final DCMotor leaderMotorDCMotors = DCMotor.getKrakenX60Foc(1);
    private final LinearSystem<N2, N1, N2> leaderMotorFlywheelSystem = LinearSystemId
            .createDCMotorSystem(leaderMotorDCMotors, 0.004, kGearRatio);
    private final DCMotorSim leaderMotorFlywheelSim = new DCMotorSim(leaderMotorFlywheelSystem, leaderMotorDCMotors);

    private static final double kSimLoopPeriod = 0.002; // 2 ms
    private Notifier simNotifier = null;
    private double lastSimTime = 0.0;

    /* Mechanism2d visualization for flywheel leaderMotor */
    private final Mechanism2d leaderMotorMech2d = new Mechanism2d(2, 2);
    private final MechanismLigament2d leaderMotorFlywheelMech2d = leaderMotorMech2d
            .getRoot("Flywheel Root leaderMotor", 1, 1)
            .append(new MechanismLigament2d("Flywheel leaderMotor", 1, 0));

    /** Configs common across all motors. */
    private static final TalonFXConfiguration motorTalonFXInitialConfigs = new TalonFXConfiguration()
            .withMotorOutput(
                    new MotorOutputConfigs()
                            .withNeutralMode(NeutralModeValue.Brake))
            .withCurrentLimits(
                    new CurrentLimitsConfigs()
                            .withStatorCurrentLimit(Amps.of(120))
                            .withStatorCurrentLimitEnable(true)
                            .withSupplyCurrentLimit(Amps.of(60))
                            .withSupplyCurrentLimitEnable(true));

    /** Configs for {@link #leaderMotor}. */
    private final TalonFXConfiguration leaderMotorConfigs = motorTalonFXInitialConfigs.clone()
            .withMotorOutput(
                    motorTalonFXInitialConfigs.MotorOutput.clone()
                            .withInverted(InvertedValue.Clockwise_Positive))
            .withFeedback(
                    motorTalonFXInitialConfigs.Feedback.clone()
                            .withSensorToMechanismRatio(1 / 1.5))
            .withSlot0(
                    motorTalonFXInitialConfigs.Slot0.clone()
                            .withKP(0.1368)
                            .withKI(0)
                            .withKD(0)
                            .withKS(0.38449)
                            .withKV(0.086321)
                            .withKA(0));

    public Flywheel() {
        for (int i = 0; i < kNumConfigAttempts; ++i) {
            var status = leaderMotor.getConfigurator().apply(leaderMotorConfigs);

            if (status.isOK())
                break;
        }
        for (int i = 0; i < kNumConfigAttempts; ++i) {
            var status = followerMotor.getConfigurator().apply(motorTalonFXInitialConfigs);

            if (status.isOK())
                break;
        }

        /* coast by default */
        coast();

        SmartDashboard.putData("Flywheel leaderMotor", leaderMotorMech2d);

        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * @return The leaderMotorVelocity of the flywheel
     */
    public AngularVelocity getleaderMotorVelocity() {
        return leaderMotorVelocity.getValue();
    }

    /**
     * @return The leaderMotorTorqueCurrent of the flywheel
     */
    public Current getleaderMotorTorqueCurrent() {
        return leaderMotorTorqueCurrent.getValue();
    }

    public boolean isNearTarget(AngularVelocity threshold) {
        return leaderMotorVelocity.isNear(RotationsPerSecond.of(leaderMotorSetpointRequest.Velocity), threshold);
    }

    /**
     * Drives the flywheel to the provided velocity setpoint.
     *
     * @param setpoint The setpoint to apply
     */
    public void setTargetSetpoint(FlywheelSetpoint setpoint) {
        leaderMotorSetpointRequest.withVelocity(setpoint.leaderMotorTarget);
        leaderMotor.setControl(leaderMotorSetpointRequest);
        followerMotor.setControl(followerMotorSetpointRequest);
    }

    /**
     * Drives the flywheel to the provided velocity (rotations per second).
     *
     * @param velocityRPS Target velocity in rotations per second
     */
    public void setTarget(double velocityRPS) {
        leaderMotorSetpointRequest.withVelocity(velocityRPS);
        leaderMotor.setControl(leaderMotorSetpointRequest);
        followerMotor.setControl(followerMotorSetpointRequest);
    }

    /**
     * Stops driving the Flywheel. We use coast so no energy is used during the
     * braking event.
     */
    public void coast() {
        leaderMotor.setControl(coastRequest);
    }

    public void periodic() {
        /* refresh all status signals */
        BaseStatusSignal.refreshAll(
                leaderMotorVelocity,
                leaderMotorTorqueCurrent);

        leaderMotorFlywheelMech2d.setLength(
                leaderMotorVelocity.getValueAsDouble() / 100.0);
    }

    private void startSimThread() {
        leaderMotor.getSimState().Orientation = ChassisReference.CounterClockwise_Positive;
        leaderMotor.getSimState().setMotorType(TalonFXSimState.MotorType.KrakenX60);

        lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        simNotifier = new Notifier(() -> {
            /* Calculate the time delta */
            final double currentTime = Utils.getCurrentTimeSeconds();
            final double deltaTime = currentTime - lastSimTime;
            lastSimTime = currentTime;

            final var leaderMotorSim = leaderMotor.getSimState();

            /* First set the supply voltage of all the devices */
            leaderMotorSim.setSupplyVoltage(RobotController.getBatteryVoltage());

            /* Then calculate the new velocity of the simulated flywheel */
            leaderMotorFlywheelSim.setInputVoltage(leaderMotorSim.getMotorVoltage());
            leaderMotorFlywheelSim.update(deltaTime);

            /* Apply the new rotor velocity to the motors (before gear ratio) */
            leaderMotorSim.setRawRotorPosition(
                    Radians.of(leaderMotorFlywheelSim.getAngularPositionRad() * kGearRatio));
            leaderMotorSim.setRotorVelocity(
                    RadiansPerSecond.of(leaderMotorFlywheelSim.getAngularVelocityRadPerSec() * kGearRatio));
        });
        simNotifier.startPeriodic(kSimLoopPeriod);
    }

    private final VoltageOut m_voltReq = new VoltageOut(0.0);

    public void runSysid(Voltage volts) {
        leaderMotor.setControl(m_voltReq.withOutput(volts.in(Volts)));
        followerMotor.setControl(followerMotorSetpointRequest);
    }
}